name: Upload attachments from Jira
run-name: Upload attachments from ${{ github.event.inputs.issue_key }} to the repository
on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: Issue key
        required: true

env:
  JIRA_PAT: ${{ secrets.JIRA_PAT }}
  ISSUE_KEY: ${{ github.event.inputs.issue_key }}
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Download attachments
        run: |
          chmod +x .github/scripts/download_attachments.sh
          . ./.github/scripts/download_attachments.sh
          
          
          # TODO AVAILABLE IN GIT STEP FOR COMPARISON@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
          #********************# WORKAROUND #********************#
          printf "%s\n" "${downloaded[@]}" > ./jira_temp/arr.txt
          #********************# WORKAROUND #********************#
          
      - name: Move files to config folder TODO FILTERING
        run: |
          mv jira_temp/*.csv config/
          # rm -rf jira_temp ###########################################################
      - name: Configure git
        run: |
          git config --global user.email "rafaumichalak1@gmail.com"
          git config --global user.name "Rafmic"
      - name: Add files to repo
        run: |
          #********************# WORKAROUND #********************#
            readarray -t downloaded < ./jira_temp/arr.txt
            rm -rf jira_temp
            changed_files=( $(git status --porcelain | cut -c4-) )
            echo "Files that were already in the repository:"
            echo ${downloaded[@]} ${changed_files[@]} | tr ' ' '\n' | sort | uniq -u
          #********************# WORKAROUND #********************#

          if [[ $(git status --porcelain) ]]; then
            # COMPARE @changed_files WITH downloaded TO POST A COMMENT ABOUT FILES WHICH WERE NOT ADDED TO REPOSITORY @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
            
            echo -e "\nAdding comment to ${ISSUE_KEY} with a list of added/modified file(s)\n"
            curl -Ssfo /dev/null -L "http://localhost:8080/rest/api/2/issue/${ISSUE_KEY}/comment" \
                 -H "Content-Type: application/json" \
                 -H "Authorization: Bearer ${JIRA_PAT}" \
                 -d '{
                   "body": "List of files that were added to the repository: \n'"$(printf '* %s\\n' "${changed_files[@]}")"'\nTo view logs go to: '"${RUN_URL}"'\n"
                 }'
            
            git add .
            git commit -m "Add config files from $ISSUE_KEY issue"
            git push
          else
            echo "Nothing to commit!"
            curl -Ssfo /dev/null -L "http://localhost:8080/rest/api/2/issue/${ISSUE_KEY}/comment" \
                 -H "Content-Type: application/json" \
                 -H "Authorization: Bearer ${JIRA_PAT}" \
                 -d '{
                   "body": "No changes were made to the repository.\nTo view logs go to: '"${RUN_URL}"'\n"
                 }'
          fi
