name: Test run
run-name: ${{ github.event_name == 'push' && format('Attempting to refresh {0} workspace', github.ref_name)
          || github.event_name == 'pull_request' && format('Testing PR to {0}', github.event.pull_request.base.ref) }} 
on:
  push:
    branches:
      - dev
      - qa
      - main
  pull_request:
    branches:
      - dev
      - qa
      - main

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4      
      - name: Run tests
        run: |
          python3 -m pytest -s -v | tee results.log
      - name: Comment PR
        if: github.event_name == 'pull_request'
        run: |
          echo ${{ secrets.NIEISTNIEJACY }}
          echo ${{ github.event.number }}
          
          RESULTS=$(cat results.log)
          TEST=$(echo "${RESULTS//$'\n'/<br>}")
          echo $TEST
          
          curl -Ss -H "Authorization: token ${{ secrets.PR_PAT }}" \
          -X POST -d '{"body": '"${TEST}"'}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
          
  refresh-dev:
    runs-on: self-hosted
    needs: run-tests
    if: github.event_name == 'push' && github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v4      
      - name: Configure git
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          
  refresh-qa:
    runs-on: self-hosted
    needs: run-tests
    if: github.event_name == 'push' && github.ref_name == 'qa'
    steps:
      - uses: actions/checkout@v4      
      - name: Configure git
        run: |
          git config --global user.email "rafal.michalak@bitpeak.pl"
          git config --global user.name "RafalMichalakBP"
