name: Test run
run-name: Test run
on:
  push:
    branches:
      - dev
      - qa
      - main
  pull_request:
    types: [opened]
    branches:
      - dev
      - qa
      - main
    

jobs:
  run-tests:
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4      
      - name: Run tests
        run: echo "testing ....."
  refresh-dev:
    runs-on: self-hosted
    needs: run-tests
    if: github.base_ref == 'dev' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4      
      - name: Configure git
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
  refresh-qa:
    runs-on: self-hosted
    needs: run-tests
    if: github.base_ref == 'qa' && github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4      
      - name: Configure git
        run: |
          git config --global user.email "rafal.michalak@bitpeak.pl"
          git config --global user.name "RafalMichalakBP"
