name: Test run
run-name: Test run
on:
  pull_request:
    types: [opened]

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4      
      - name: Run tests
        run: echo "testing ....."
  refresh-dev:
    runs-on: self-hosted
    needs: run-tests
    if: github.base_ref == 'dev'
    steps:
      - uses: actions/checkout@v4      
      - name: Configure git
        run: |
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
  refresh-qa:
    runs-on: self-hosted
    needs: run-tests
    if: github.base_ref == 'qa'
    steps:
      - uses: actions/checkout@v4      
      - name: Configure git
        run: |
          git config --global user.email "rafal.michalak@bitpeak.pl"
          git config --global user.name "RafalMichalakBP"
